// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type ExampleCity struct {
	ID              string
	Name            string
	Population      int64
	FoundingIso8601 string
}
