// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const getAllCities = `-- name: GetAllCities :many
SELECT id, name, population, founding_iso8601 FROM example_cities
`

func (q *Queries) GetAllCities(ctx context.Context) ([]ExampleCity, error) {
	rows, err := q.db.QueryContext(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExampleCity
	for rows.Next() {
		var i ExampleCity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Population,
			&i.FoundingIso8601,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
